/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.pf.formas;

import java.util.LinkedList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.pf.clases.Asistente;
import uam.pvoe.pf.clases.Taller;
import uam.pvoe.pf.operaciones.GestionAsistentes;
import uam.pvoe.pf.operaciones.GestionTalleres;

/**
 *
 * @author Cristian Emanuel Ceron Franco
 */
public class AdministracionFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministracionFrm.class.getName());

    private LinkedList<Asistente> listaAsistentesGlobal = new LinkedList<>();
    private ButtonGroup grupoGenero;

    /**
     * Escribe un registro de auditoría en el archivo bitacora.dat
     */
    private void registrarEnBitacora(String accion, String detalles, String motivo) {
        // El parámetro 'true' en FileWriter indica que vamos a AGREGAR al final del archivo (Append)
        try (java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter("bitacora.dat", true))) {

            // Obtenemos la fecha y hora actual del sistema
            java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
            java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            String fechaHora = ahora.format(formato);

            // Armamos la línea. Si no hay motivo, ponemos "N/A"
            String textoMotivo = (motivo == null || motivo.trim().isEmpty()) ? "N/A" : motivo.trim();
            String linea = "[" + fechaHora + "] ACCIÓN: " + accion + " | DETALLES: " + detalles + " | MOTIVO: " + textoMotivo;

            bw.write(linea);
            bw.newLine();

        } catch (Exception e) {
            System.out.println("Error al escribir en la bitácora: " + e.getMessage());
        }
    }

    /**
     * Creates new form ConsultaAsistentesFrm
     */
    public AdministracionFrm() {
        initComponents();
        ocultarPaneles();
        configurarTabla();
        cargarTodosLosAsistentes();
        configurarControles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConsulta = new javax.swing.JPanel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelContacto = new javax.swing.JLabel();
        lblTelEmergencia = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelC = new javax.swing.JTextField();
        txtTelE = new javax.swing.JTextField();
        lblPrimerApellido = new javax.swing.JLabel();
        lblSegundoApellido = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtADir = new javax.swing.JTextArea();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        btnGuardarAsistente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelTalleres = new javax.swing.JPanel();
        lblTalleres = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblCostoMaterial = new javax.swing.JLabel();
        cbTalleres = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        btnBajaTaller = new javax.swing.JButton();
        btnGuardarTaller = new javax.swing.JButton();
        lblAsistente = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        chMaterial = new javax.swing.JCheckBox();
        lblMotivo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAMotivo = new javax.swing.JTextArea();
        txtAsistente = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtCostoMaterial = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        lblHorario = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        lblHorariosDisp = new javax.swing.JLabel();
        cbHorariosDisp = new javax.swing.JComboBox<>();
        btnCambiarHorario = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa de la Cultura – UAM Azcapotzalco :: Administración de la Información");
        setMaximumSize(new java.awt.Dimension(873, 746));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        pnlConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblBusca.setText("Busca por Nombre o ID:");

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbConsulta);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaLayout.createSequentialGroup()
                        .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBusca)
                            .addGroup(pnlConsultaLayout.createSequentialGroup()
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnBuscar)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles del Asistente Selecionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnlDatos.setToolTipText("");

        lblId.setText("id");

        lblNombre.setText("Nombre");

        lblEdad.setText("Edad");

        lblGenero.setText("Genero");

        lblDireccion.setText("Dirección");

        lblTelContacto.setText("Télefono de contacto");

        lblTelEmergencia.setText("Télefono de emergencia");

        txtId.setEditable(false);

        lblPrimerApellido.setText("Primer Apellido");

        lblSegundoApellido.setText("Segundo Apellido");

        txtPrimerApellido.addActionListener(this::txtPrimerApellidoActionPerformed);

        txtADir.setColumns(20);
        txtADir.setRows(5);
        jScrollPane3.setViewportView(txtADir);

        rbMasculino.setText("Masculino");

        rbFemenino.setText("Femenino");

        rbOtro.setText("Otro");

        btnGuardarAsistente.setText("Guardar");
        btnGuardarAsistente.addActionListener(this::btnGuardarAsistenteActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosLayout.createSequentialGroup()
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosLayout.createSequentialGroup()
                                .addComponent(lblGenero)
                                .addGap(18, 18, 18)
                                .addComponent(rbMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(rbFemenino)
                                .addGap(18, 18, 18)
                                .addComponent(rbOtro)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(lblEdad)
                                .addGap(74, 74, 74)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(lblDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosLayout.createSequentialGroup()
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSegundoApellido)
                                    .addComponent(lblPrimerApellido)
                                    .addComponent(lblNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addComponent(txtPrimerApellido)
                                    .addComponent(txtSegundoApellido)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosLayout.createSequentialGroup()
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelEmergencia)
                                    .addComponent(lblTelContacto))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelC)
                                    .addComponent(txtTelE))))
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnGuardarAsistente))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)))))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerApellido)
                    .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoApellido)
                    .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino)
                    .addComponent(rbOtro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar))
                    .addComponent(lblTelContacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelEmergencia)
                    .addComponent(txtTelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAsistente))
                .addGap(17, 17, 17))
        );

        panelTalleres.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Talleres y Cuotas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblTalleres.setText("Taller(es): ");

        lblCosto.setText("Costo taller:");

        lblCostoMaterial.setText("Costo material:");

        cbTalleres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTalleres.addActionListener(this::cbTalleresActionPerformed);

        lblTotal.setText("Total:");

        btnBajaTaller.setText("Baja del taller");
        btnBajaTaller.addActionListener(this::btnBajaTallerActionPerformed);

        btnGuardarTaller.setText("Guardar Cambios");
        btnGuardarTaller.addActionListener(this::btnGuardarTallerActionPerformed);

        lblAsistente.setText("Asistente seleccionado: ");

        lblMaterial.setText("Material:");

        chMaterial.addActionListener(this::chMaterialActionPerformed);

        lblMotivo.setText("Motivo (Opcional)");

        txtAMotivo.setColumns(20);
        txtAMotivo.setRows(5);
        jScrollPane2.setViewportView(txtAMotivo);

        txtAsistente.setEditable(false);

        lblHorario.setText("Horario:");

        lblHorariosDisp.setText("Horarios Disponibles");

        cbHorariosDisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbHorariosDisp.addActionListener(this::cbHorariosDispActionPerformed);

        btnCambiarHorario.setText("Cambiar Horario");
        btnCambiarHorario.addActionListener(this::btnCambiarHorarioActionPerformed);

        javax.swing.GroupLayout panelTalleresLayout = new javax.swing.GroupLayout(panelTalleres);
        panelTalleres.setLayout(panelTalleresLayout);
        panelTalleresLayout.setHorizontalGroup(
            panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTalleresLayout.createSequentialGroup()
                        .addComponent(lblCosto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCosto)
                        .addGap(431, 431, 431))
                    .addGroup(panelTalleresLayout.createSequentialGroup()
                        .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTalleresLayout.createSequentialGroup()
                                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTalleresLayout.createSequentialGroup()
                                        .addComponent(lblHorario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHorario))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTalleresLayout.createSequentialGroup()
                                        .addComponent(lblTalleres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCambiarHorario)
                                .addGap(99, 99, 99)
                                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHorariosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHorariosDisp)))
                            .addGroup(panelTalleresLayout.createSequentialGroup()
                                .addComponent(lblAsistente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMotivo))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(panelTalleresLayout.createSequentialGroup()
                        .addComponent(lblCostoMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostoMaterial)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chMaterial)
                        .addGap(348, 348, 348))
                    .addGroup(panelTalleresLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal)
                        .addGap(431, 431, 431))
                    .addGroup(panelTalleresLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(btnGuardarTaller)
                        .addGap(18, 18, 18)
                        .addComponent(btnBajaTaller)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelTalleresLayout.setVerticalGroup(
            panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsistente)
                    .addComponent(txtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTalleres)
                    .addComponent(cbTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorariosDisp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHorariosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCosto)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chMaterial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCostoMaterial)
                        .addComponent(txtCostoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaterial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMotivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardarTaller)
                        .addComponent(btnBajaTaller)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuFrm menu = new MenuFrm();
        menu.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String criterio = txtBusca.getText().trim();
        actualizarTablaDesdeLista(criterio);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultaMouseClicked
        // TODO add your handling code here:
        int fila = tbConsulta.getSelectedRow();

        if (fila != -1) {
            String idSeleccionado = tbConsulta.getValueAt(fila, 0).toString();

            GestionAsistentes ge = new GestionAsistentes();
            String[] datos = ge.obtenerAsistentePorId(idSeleccionado);

            if (datos != null && datos.length >= 9) {

                txtId.setText(datos[0]);
                txtNombre.setText(datos[1]);
                txtSegundoApellido.setText(datos[3]);
                txtPrimerApellido.setText(datos[2]);
                txtEdad.setText(datos[4]);

                String genero = datos[5];
                if (genero.equalsIgnoreCase("Masculino")) {
                    rbMasculino.setSelected(true);
                } else if (genero.equalsIgnoreCase("Femenino")) {
                    rbFemenino.setSelected(true);
                } else {
                    rbOtro.setSelected(true);
                }

                txtADir.setText(datos[6]);
                txtTelC.setText(datos[7]);
                txtTelE.setText(datos[8]);

                txtAsistente.setText(datos[1] + " " + datos[2] + " " + datos[3]);

                cbTalleres.removeAllItems();

                boolean tieneTalleres = false;
                if (datos.length > 9) {
                    for (int i = 9; i < datos.length; i += 4) {
                        cbTalleres.addItem(datos[i]);
                        tieneTalleres = true;
                    }
                }

                if (!tieneTalleres) {
                    cbTalleres.addItem("Sin talleres inscritos");
                    txtHorario.setText("");
                    txtCosto.setText("");
                    txtCostoMaterial.setText("");
                    txtTotal.setText("");
                    chMaterial.setSelected(false);
                } else {
                    cbTalleres.setSelectedIndex(0);
                }

                pnlDatos.setVisible(true);
                panelTalleres.setVisible(true);
            }
        }
    }//GEN-LAST:event_tbConsultaMouseClicked

    private void cbTalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTalleresActionPerformed
        // TODO add your handling code here:
        lblHorariosDisp.setVisible(false);
        cbHorariosDisp.setVisible(false);
        if (cbTalleres.getSelectedItem() == null) {
            return;
        }

        String tallerSeleccionado = cbTalleres.getSelectedItem().toString();

        if (tallerSeleccionado.equals("Sin talleres inscritos")) {
            txtHorario.setText("");
            txtCosto.setText("");
            txtCostoMaterial.setText("");
            txtTotal.setText("");
            chMaterial.setSelected(false);
            return;
        }

        int fila = tbConsulta.getSelectedRow();
        if (fila == -1) {
            return;
        }

        String idSeleccionado = tbConsulta.getValueAt(fila, 0).toString();

        GestionAsistentes ge = new GestionAsistentes();
        String[] datos = ge.obtenerAsistentePorId(idSeleccionado);

        if (datos != null && datos.length > 9) {

            for (int i = 9; i < datos.length; i += 4) {

                if (datos[i].equals(tallerSeleccionado)) {

                    txtHorario.setText(datos[i + 1]);

                    boolean usaMaterial = datos[i + 2].equalsIgnoreCase("Si");
                    chMaterial.setSelected(usaMaterial);

                    txtTotal.setText(datos[i + 3]);

                    GestionTalleres gt = new GestionTalleres();
                    LinkedList<Taller> listaTalleres = gt.listaTalleres();

                    for (uam.pvoe.pf.clases.Taller t : listaTalleres) {
                        if (t.getNombre().equals(tallerSeleccionado)) {

                            txtCosto.setText(String.valueOf(t.getCostoBase()));

                            if (usaMaterial) {
                                txtCostoMaterial.setText(String.valueOf(t.getCostoMaterial()));
                            } else {
                                txtCostoMaterial.setText("0.0");
                            }
                            break;
                        }
                    }
                    break;
                }
            }
        }
    }//GEN-LAST:event_cbTalleresActionPerformed

    private void btnBajaTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaTallerActionPerformed
        // TODO add your handling code here:
        if (cbTalleres.getSelectedItem() == null) {
            return;
        }
        String tallerSeleccionado = cbTalleres.getSelectedItem().toString();

        if (tallerSeleccionado.equals("Sin talleres inscritos")) {
            JOptionPane.showMessageDialog(this,
                    "El asistente no tiene talleres para dar de baja.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int fila = tbConsulta.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor seleccione un asistente de la tabla.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String idAsistente = tbConsulta.getValueAt(fila, 0).toString();

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea dar de baja al asistente del taller de " + tallerSeleccionado + "?",
                "Confirmar Baja",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            GestionAsistentes ge = new GestionAsistentes();
            boolean exito = ge.darDeBajaTaller(idAsistente, tallerSeleccionado);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Baja realizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                String detalles = "Se dio de baja al ID: " + idAsistente + " del taller: " + tallerSeleccionado;
                registrarEnBitacora("BAJA TALLER", detalles, txtAMotivo.getText());
                txtAMotivo.setText(""); // Limpiamos el motivo para la próxima

                String idActual = idAsistente;
                cargarTodosLosAsistentes();
                actualizarTablaDesdeLista(txtBusca.getText().trim());

                for (int i = 0; i < tbConsulta.getRowCount(); i++) {
                    if (tbConsulta.getValueAt(i, 0).toString().equals(idActual)) {
                        tbConsulta.setRowSelectionInterval(i, i);
                        tbConsultaMouseClicked(null);
                        cbTalleres.setSelectedItem(tallerSeleccionado);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al intentar dar de baja el taller.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBajaTallerActionPerformed

    private void chMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chMaterialActionPerformed
        // TODO add your handling code here:
        if (cbTalleres.getSelectedItem() == null) {
            return;
        }
        String tallerSeleccionado = cbTalleres.getSelectedItem().toString();

        if (tallerSeleccionado.equals("Sin talleres inscritos")) {
            chMaterial.setSelected(false);
            return;
        }

        GestionTalleres gt = new GestionTalleres();
        LinkedList<Taller> listaTalleres = gt.listaTalleres();

        double costoMatCatalogo = 0.0;
        for (uam.pvoe.pf.clases.Taller t : listaTalleres) {
            if (t.getNombre().equals(tallerSeleccionado)) {
                costoMatCatalogo = t.getCostoMaterial();
                break;
            }
        }

        if (chMaterial.isSelected()) {
            txtCostoMaterial.setText(String.valueOf(costoMatCatalogo));
        } else {
            txtCostoMaterial.setText("0.0");
        }

        calcularSumaTotal();
    }//GEN-LAST:event_chMaterialActionPerformed

    private void btnGuardarTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTallerActionPerformed
        // TODO add your handling code here:
        if (cbTalleres.getSelectedItem() == null) {
            return;
        }
        String tallerSeleccionado = cbTalleres.getSelectedItem().toString();

        if (tallerSeleccionado.equals("Sin talleres inscritos")) {
            JOptionPane.showMessageDialog(this,
                    "El asistente no tiene talleres para actualizar.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int fila = tbConsulta.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor seleccione un asistente de la tabla.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idAsistente = tbConsulta.getValueAt(fila, 0).toString();
        String nuevoHorario = txtHorario.getText().trim();
        boolean conMaterial = chMaterial.isSelected();
        String nuevoTotal = txtTotal.getText().trim();

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Desea guardar los cambios para el taller de " + tallerSeleccionado + "?\n"
                + "Nuevo Total: $" + nuevoTotal,
                "Confirmar Actualización",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            GestionAsistentes ge = new GestionAsistentes();
            boolean exito = ge.actualizarInscripcionTaller(idAsistente, tallerSeleccionado, nuevoHorario, conMaterial, nuevoTotal);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                String detalles = "Actualización de Horario/Material para ID: " + idAsistente + " en taller: " + tallerSeleccionado;
                registrarEnBitacora("ACTUALIZAR TALLER", detalles, txtAMotivo.getText());
                txtAMotivo.setText(""); // Limpiamos el motivo

                String idActual = idAsistente;
                cargarTodosLosAsistentes();
                actualizarTablaDesdeLista(txtBusca.getText().trim());

                for (int i = 0; i < tbConsulta.getRowCount(); i++) {
                    if (tbConsulta.getValueAt(i, 0).toString().equals(idActual)) {
                        tbConsulta.setRowSelectionInterval(i, i);
                        tbConsultaMouseClicked(null);
                        cbTalleres.setSelectedItem(tallerSeleccionado);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al intentar guardar los cambios.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarTallerActionPerformed

    private void btnCambiarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarHorarioActionPerformed
        // TODO add your handling code here:
        if (cbTalleres.getSelectedItem() == null) {
            return;
        }
        String tallerSeleccionado = cbTalleres.getSelectedItem().toString();

        if (tallerSeleccionado.equals("Sin talleres inscritos")) {
            return;
        }

        cbHorariosDisp.removeAllItems();

        GestionTalleres gt = new GestionTalleres();
        LinkedList<Taller> listaTalleres = gt.listaTalleres();

        for (Taller t : listaTalleres) {
            if (t.getNombre().equals(tallerSeleccionado)) {
                String[] horariosOficiales = t.getHorarios();
                for (int i = 0; i < horariosOficiales.length; i++) {
                    cbHorariosDisp.addItem(horariosOficiales[i]);
                }
                break;
            }
        }

        lblHorariosDisp.setVisible(true);
        cbHorariosDisp.setVisible(true);
    }//GEN-LAST:event_btnCambiarHorarioActionPerformed

    private void cbHorariosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHorariosDispActionPerformed
        // TODO add your handling code here:
        if (cbHorariosDisp.getSelectedItem() != null) {
            txtHorario.setText(cbHorariosDisp.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbHorariosDispActionPerformed

    private void btnGuardarAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsistenteActionPerformed
        // TODO add your handling code here:
        int fila = tbConsulta.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un asistente primero.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id = txtId.getText();
        String nom = txtNombre.getText().trim();
        String ap1 = txtSegundoApellido.getText().trim();
        String ap2 = txtPrimerApellido.getText().trim();
        String edad = txtEdad.getText().trim();
        String dir = txtADir.getText().trim();
        String telC = txtTelC.getText().trim();
        String telE = txtTelE.getText().trim();

        String gen = rbMasculino.isSelected() ? "Masculino" : (rbFemenino.isSelected() ? "Femenino" : "Otro");

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Desea actualizar los datos personales de " + nom + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            GestionAsistentes ge = new GestionAsistentes();
            if (ge.actualizarDatosAsistente(id, nom, ap1, ap2, edad, gen, dir, telC, telE)) {
                JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");

                String detalles = "Se actualizaron los datos personales del ID: " + id + " (" + nom + " " + ap1 + ")";
                registrarEnBitacora("ACTUALIZAR DATOS", detalles, "");

                String idActual = id;
                cargarTodosLosAsistentes();
                actualizarTablaDesdeLista(txtBusca.getText().trim());

                for (int i = 0; i < tbConsulta.getRowCount(); i++) {
                    if (tbConsulta.getValueAt(i, 0).toString().equals(idActual)) {
                        tbConsulta.setRowSelectionInterval(i, i);
                        tbConsultaMouseClicked(null);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarAsistenteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tbConsulta.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el asistente que desea eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id = txtId.getText();
        String nombre = txtNombre.getText();

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¡ATENCIÓN! ¿Está absolutamente seguro de que desea ELIMINAR a " + nombre + " y todos sus talleres inscritos del sistema?\nEsta acción no se puede deshacer.",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            GestionAsistentes ge = new GestionAsistentes();

            if (ge.eliminarAsistente(id)) {
                JOptionPane.showMessageDialog(this, "El asistente ha sido eliminado del sistema.");

                String detalles = "Se ELIMINÓ por completo al ID: " + id + " (" + nombre + ")";
                registrarEnBitacora("ELIMINAR ASISTENTE", detalles, "Baja definitiva del sistema");

                cargarTodosLosAsistentes();
                tbConsulta.clearSelection();
                ocultarPaneles();
                txtBusca.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Error al intentar eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdministracionFrm().setVisible(true));
    }

    private void ocultarPaneles() {
        pnlDatos.setVisible(false);
        panelTalleres.setVisible(false);
        lblHorariosDisp.setVisible(false);
        cbHorariosDisp.setVisible(false);
    }

    private void cargarTodosLosAsistentes() {
        GestionAsistentes ge = new GestionAsistentes();
        listaAsistentesGlobal = ge.obtenerTodosLosAsistentes();

        actualizarTablaDesdeLista("");
    }

    private void actualizarTablaDesdeLista(String criterio) {
        ocultarPaneles();
        tbConsulta.clearSelection();

        DefaultTableModel modelo = (DefaultTableModel) tbConsulta.getModel();
        modelo.setRowCount(0);

        for (Asistente a : listaAsistentesGlobal) {
            String id = a.getId();
            String nombreCompleto = a.getNombre() + " " + a.getPrimerApellido() + " " + a.getSegundoApellido();

            if (criterio.isEmpty() || id.equals(criterio) || nombreCompleto.toLowerCase().contains(criterio.toLowerCase())) {

                modelo.addRow(new Object[]{id, a.getNombre(), a.getPrimerApellido(), a.getSegundoApellido()});
            }
        }

        tbConsulta.revalidate();
        tbConsulta.repaint();
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Nombre", "Primer Apellido", "Segundo Apellido"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbConsulta.setModel(modelo);
    }

    private void configurarControles() {
        grupoGenero = new ButtonGroup();
        grupoGenero.add(rbMasculino);
        grupoGenero.add(rbFemenino);
        grupoGenero.add(rbOtro);
    }

    private void calcularSumaTotal() {
        try {
            // 1. Tomamos el texto. Si está vacío, usamos "0.0"
            String textoCostoBase = txtCosto.getText().trim().isEmpty() ? "0.0" : txtCosto.getText().trim();
            String textoCostoMat = txtCostoMaterial.getText().trim().isEmpty() ? "0.0" : txtCostoMaterial.getText().trim();

            // 2. Convertimos a Double
            double costoBase = Double.parseDouble(textoCostoBase);
            double costoMat = Double.parseDouble(textoCostoMat);

            // 3. Sumamos y ponemos el resultado en la caja de Total
            double total = costoBase + costoMat;
            txtTotal.setText(String.valueOf(total));

        } catch (NumberFormatException e) {
            txtTotal.setText("0.0");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaTaller;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarHorario;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarAsistente;
    private javax.swing.JButton btnGuardarTaller;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbHorariosDisp;
    private javax.swing.JComboBox<String> cbTalleres;
    private javax.swing.JCheckBox chMaterial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAsistente;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCostoMaterial;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblHorariosDisp;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrimerApellido;
    private javax.swing.JLabel lblSegundoApellido;
    private javax.swing.JLabel lblTalleres;
    private javax.swing.JLabel lblTelContacto;
    private javax.swing.JLabel lblTelEmergencia;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelTalleres;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JTable tbConsulta;
    private javax.swing.JTextArea txtADir;
    private javax.swing.JTextArea txtAMotivo;
    private javax.swing.JTextField txtAsistente;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtCostoMaterial;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtTelC;
    private javax.swing.JTextField txtTelE;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
