/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.pf.formas;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.pf.clases.Asistente;
import uam.pvoe.pf.clases.Taller;
import uam.pvoe.pf.compartido.Compartido;
import uam.pvoe.pf.operaciones.GestionAsistentes;
import uam.pvoe.pf.operaciones.GestionTalleres;

/**
 *
 * @author Cristian Emanuel Ceron Franco
 */
public class InscripcionTalleresFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InscripcionTalleresFrm.class.getName());
    private LinkedList<Asistente> listaAsistentesGlobal = new LinkedList<>();

    /**
     * Creates new form InscripcionTalleresFrm
     */
    public InscripcionTalleresFrm() {
        initComponents();
        Compartido.idAsistenteSeleccionado = null;
        configurarTabla();
        cargarTodosLosAsistentes();
        llenarListaTalleres();
        ocultarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIncripcion = new javax.swing.JPanel();
        lblTaller = new javax.swing.JLabel();
        cbTaller = new javax.swing.JComboBox<>();
        lblHorario = new javax.swing.JLabel();
        cbHorario = new javax.swing.JComboBox<>();
        lblMaterial = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblCostoM = new javax.swing.JLabel();
        lblCostoTotal = new javax.swing.JLabel();
        chMaterial = new javax.swing.JCheckBox();
        txtCosto = new javax.swing.JTextField();
        txtCostoMaterial = new javax.swing.JTextField();
        txtCostoTotal = new javax.swing.JTextField();
        lblBusca = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbAsistentes = new javax.swing.JTable();
        btnInscribir = new javax.swing.JButton();
        lblInstructor = new javax.swing.JLabel();
        txtInstructor = new javax.swing.JTextField();
        lblAsistente = new javax.swing.JLabel();
        txtAsistente = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa de la Cultura – UAM Azcapotzalco :: Inscripción del Asistente a los Talleres");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panelIncripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incripción de Talleres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblTaller.setText("Taller");

        cbTaller.addActionListener(this::cbTallerActionPerformed);

        lblHorario.setText("Horario");

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMaterial.setText("Adquirir material requerido");

        lblCosto.setText("Costo: ");

        lblCostoM.setText("Costo material:");

        lblCostoTotal.setText("Costo Total:");

        chMaterial.addActionListener(this::chMaterialActionPerformed);

        txtCosto.setEditable(false);

        txtCostoMaterial.setEditable(false);

        txtCostoTotal.setEditable(false);

        lblBusca.setText("Busca por Nombre o ID:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        tbAsistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAsistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAsistentesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbAsistentes);

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(this::btnInscribirActionPerformed);

        lblInstructor.setText("Instructor");

        txtInstructor.setEditable(false);
        txtInstructor.addActionListener(this::txtInstructorActionPerformed);

        lblAsistente.setText("Asistente seleccionado: ");

        txtAsistente.setEditable(false);

        javax.swing.GroupLayout panelIncripcionLayout = new javax.swing.GroupLayout(panelIncripcion);
        panelIncripcion.setLayout(panelIncripcionLayout);
        panelIncripcionLayout.setHorizontalGroup(
            panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncripcionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIncripcionLayout.createSequentialGroup()
                        .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelIncripcionLayout.createSequentialGroup()
                                .addComponent(lblCostoTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCostoTotal))
                            .addGroup(panelIncripcionLayout.createSequentialGroup()
                                .addComponent(lblCostoM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCostoMaterial))
                            .addGroup(panelIncripcionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblCosto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(364, 364, 364)
                        .addComponent(btnInscribir)
                        .addGap(33, 33, 33))
                    .addGroup(panelIncripcionLayout.createSequentialGroup()
                        .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHorario)
                                .addComponent(lblTaller)
                                .addComponent(cbTaller, 0, 369, Short.MAX_VALUE)
                                .addComponent(cbHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelIncripcionLayout.createSequentialGroup()
                                .addComponent(lblMaterial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chMaterial)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIncripcionLayout.createSequentialGroup()
                        .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelIncripcionLayout.createSequentialGroup()
                                .addComponent(lblInstructor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelIncripcionLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelIncripcionLayout.createSequentialGroup()
                                                .addComponent(lblBusca)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBuscar))
                                            .addGroup(panelIncripcionLayout.createSequentialGroup()
                                                .addComponent(lblAsistente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelIncripcionLayout.createSequentialGroup()
                                        .addComponent(txtInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelIncripcionLayout.setVerticalGroup(
            panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncripcionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBusca)
                    .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsistente)
                    .addComponent(txtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblTaller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTaller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstructor)
                    .addComponent(txtInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIncripcionLayout.createSequentialGroup()
                        .addComponent(lblMaterial)
                        .addGap(18, 18, 18)
                        .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCosto)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCostoM)
                            .addComponent(txtCostoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCostoTotal)
                            .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInscribir)))
                    .addComponent(chMaterial))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar)
                    .addComponent(panelIncripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelIncripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chMaterialActionPerformed
        Taller taller = (Taller) cbTaller.getSelectedItem();

        if (taller != null && taller.getNombre().compareTo("Seleccione un taller...") != 0) {

            if (chMaterial.isSelected()) {
                txtCostoMaterial.setText(String.valueOf(taller.getCostoMaterial()));
            } else {
                txtCostoMaterial.setText("0.0");
            }

            calcularSumaTotal();
        }
    }//GEN-LAST:event_chMaterialActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuFrm menu = new MenuFrm();
        menu.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        String idSeleccionado = Compartido.idAsistenteSeleccionado;
        if (idSeleccionado == null || idSeleccionado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un asistente...", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Taller taller = (Taller) cbTaller.getSelectedItem();
        if (taller == null || taller.getNombre().equals("Seleccione un taller...")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un taller...", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Recopilar todos los datos de la interfaz
        String nombreTaller = taller.getNombre();
        String horario = cbHorario.getSelectedItem().toString();
        boolean requiereMaterial = chMaterial.isSelected();
        String costoTotal = txtCostoTotal.getText();

        GestionAsistentes ge = new GestionAsistentes();

        String[] datosActuales = ge.obtenerAsistentePorId(idSeleccionado);

        if (datosActuales != null && datosActuales.length > 9) {
            for (int i = 9; i < datosActuales.length; i += 4) {
                if (datosActuales[i].equals(nombreTaller)) {
                    JOptionPane.showMessageDialog(this,
                            "El asistente ya se encuentra inscrito en el taller de " + nombreTaller + ".",
                            "Inscripción Duplicada", JOptionPane.WARNING_MESSAGE);
                    return; // Detenemos la ejecución aquí mismo
                }
            }
        }

        boolean exito = ge.guardarInscripcion(idSeleccionado, nombreTaller, horario, requiereMaterial, costoTotal);

        if (exito) {
            JOptionPane.showMessageDialog(this, "¡Inscripción guardada con éxito!");

            String idActual = Compartido.idAsistenteSeleccionado;

            cargarTodosLosAsistentes();
            actualizarTablaDesdeLista(txtBusca.getText().trim());

            for (int i = 0; i < tbAsistentes.getRowCount(); i++) {
                if (tbAsistentes.getValueAt(i, 0).toString().equals(idActual)) {
                    tbAsistentes.setRowSelectionInterval(i, i);
                    tbAsistentesMouseClicked(null);
                    break;
                }
            }
            cbTaller.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al intentar guardar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String criterio = txtBusca.getText().trim();
        actualizarTablaDesdeLista(criterio);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbAsistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAsistentesMouseClicked
        int fila = tbAsistentes.getSelectedRow();

        if (fila != -1) {
            String id = tbAsistentes.getValueAt(fila, 0).toString();
            String nombre = tbAsistentes.getValueAt(fila, 1).toString();
            String ap1 = tbAsistentes.getValueAt(fila, 2).toString();
            String ap2 = tbAsistentes.getValueAt(fila, 3).toString();

            Compartido.idAsistenteSeleccionado = id;

            txtAsistente.setText(nombre + " " + ap1 + " " + ap2);

            lblAsistente.setVisible(true);
            txtAsistente.setVisible(true);
            lblTaller.setVisible(true);
            cbTaller.setVisible(true);
        }
    }//GEN-LAST:event_tbAsistentesMouseClicked

    private void cbTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTallerActionPerformed
        Taller taller = (Taller) cbTaller.getSelectedItem();

        if (taller != null) {

            if (taller.getNombre().compareTo("Seleccione un taller...") != 0) {

                String idSeleccionado = Compartido.idAsistenteSeleccionado;
                if (idSeleccionado == null || idSeleccionado.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Por favor, seleccione primero un asistente de la tabla.",
                            "Aviso", JOptionPane.WARNING_MESSAGE);

                    cbTaller.setSelectedIndex(0);
                    return;
                }

                System.out.println("Taller seleccionado: " + taller.getNombre());

                cbHorario.removeAllItems();
                for (int i = 0; i < taller.getHorarios().length; i++) {
                    cbHorario.addItem(taller.getHorarios()[i]);
                }

                txtCosto.setText(String.valueOf(taller.getCostoBase()));
                txtInstructor.setText(taller.getInstructor());
                chMaterial.setSelected(false);
                txtCostoMaterial.setText("0.0");
                calcularSumaTotal();

                // Mostrar todos los componentes
                cbHorario.setVisible(true);
                lblHorario.setVisible(true);
                lblInstructor.setVisible(true);
                txtInstructor.setVisible(true);
                lblMaterial.setVisible(true);
                chMaterial.setVisible(true);
                lblCosto.setVisible(true);
                txtCosto.setVisible(true);
                lblCostoM.setVisible(true);
                txtCostoMaterial.setVisible(true);
                lblCostoTotal.setVisible(true);
                txtCostoTotal.setVisible(true);
                btnInscribir.setVisible(true);

            } else {
                cbHorario.setVisible(false);
                lblHorario.setVisible(false);
                lblInstructor.setVisible(false);
                txtInstructor.setVisible(false);
                lblMaterial.setVisible(false);
                chMaterial.setVisible(false);
                lblCosto.setVisible(false);
                txtCosto.setVisible(false);
                lblCostoM.setVisible(false);
                txtCostoMaterial.setVisible(false);
                lblCostoTotal.setVisible(false);
                txtCostoTotal.setVisible(false);
                btnInscribir.setVisible(false);

                cbHorario.removeAllItems();
                txtCosto.setText("");
                txtInstructor.setText("");
                txtCostoMaterial.setText("");
                txtCostoTotal.setText("");
            }
        }
    }//GEN-LAST:event_cbTallerActionPerformed

    private void txtInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InscripcionTalleresFrm().setVisible(true));
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Teléfono"}
        ) {
            // Evita que el usuario edite las celdas directamente
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tbAsistentes.setModel(modelo);
    }

    private void cargarTodosLosAsistentes() {
        GestionAsistentes ge = new GestionAsistentes();

        listaAsistentesGlobal = ge.obtenerTodosLosAsistentes();

        actualizarTablaDesdeLista("");
    }

    public void llenarListaTalleres() {
        cbTaller.removeAllItems();

        Taller tallerVacio = new Taller("Seleccione un taller...", "", new String[]{""}, 0.0, 0.0);
        cbTaller.addItem(tallerVacio);

        GestionTalleres administrar = new GestionTalleres();
        LinkedList<Taller> lista = administrar.listaTalleres();

        for (int i = 0; i < lista.size(); i++) {
            Taller taller = lista.get(i);
            cbTaller.addItem(taller);
        }
    }

    private void calcularSumaTotal() {
        try {
            String textoCostoBase = txtCosto.getText().trim().isEmpty() ? "0.0" : txtCosto.getText().trim();
            String textoCostoMat = txtCostoMaterial.getText().trim().isEmpty() ? "0.0" : txtCostoMaterial.getText().trim();

            double costoBase = Double.parseDouble(textoCostoBase);
            double costoMat = Double.parseDouble(textoCostoMat);

            double total = costoBase + costoMat;
            txtCostoTotal.setText(String.valueOf(total));

        } catch (NumberFormatException e) {
            txtCostoTotal.setText("0.0");
        }
    }

    private void ocultarComponentes() {
        lblTaller.setVisible(false);
        cbTaller.setVisible(false);
        lblAsistente.setVisible(false);
        txtAsistente.setVisible(false);

        cbHorario.setVisible(false);
        lblHorario.setVisible(false);
        lblInstructor.setVisible(false);
        txtInstructor.setVisible(false);
        lblMaterial.setVisible(false);
        chMaterial.setVisible(false);
        lblCosto.setVisible(false);
        txtCosto.setVisible(false);
        lblCostoM.setVisible(false);
        txtCostoMaterial.setVisible(false);
        lblCostoTotal.setVisible(false);
        txtCostoTotal.setVisible(false);
        btnInscribir.setVisible(false);
    }

    private void actualizarTablaDesdeLista(String criterio) {
        Compartido.idAsistenteSeleccionado = null;

        tbAsistentes.clearSelection();

        ocultarComponentes();

        DefaultTableModel modelo = (DefaultTableModel) tbAsistentes.getModel();
        modelo.setRowCount(0);

        for (Asistente a : listaAsistentesGlobal) {
            String id = a.getId();
            String nombreCompleto = a.getNombre() + " " + a.getPrimerApellido() + " " + a.getSegundoApellido();
            String telefono = a.getTelContacto();

            if (criterio.isEmpty() || id.equals(criterio) || nombreCompleto.toLowerCase().contains(criterio.toLowerCase())) {
                modelo.addRow(new Object[]{id, a.getNombre(), a.getPrimerApellido(), a.getSegundoApellido(), telefono});
            }
        }

        tbAsistentes.revalidate();
        tbAsistentes.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JComboBox<Taller> cbTaller;
    private javax.swing.JCheckBox chMaterial;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAsistente;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCostoM;
    private javax.swing.JLabel lblCostoTotal;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblInstructor;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblTaller;
    private javax.swing.JPanel panelIncripcion;
    private javax.swing.JTable tbAsistentes;
    private javax.swing.JTextField txtAsistente;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtCostoMaterial;
    private javax.swing.JTextField txtCostoTotal;
    private javax.swing.JTextField txtInstructor;
    // End of variables declaration//GEN-END:variables
}
